import 'package:max_task/models/vehicle.dart';

/// Dummy list for checked in vehicles
List<Vehicle> dummyCheckedInVehicles = [
  Vehicle(
    plateNumber: "DEF456GH",
    name: "Jane Smith",
    model: "Toyota Corolla",
    type: "Sedan",
    color: "Blue",
    champion: "John Doe",
    location: "Abuja, Nigeria",
    analyst: "Mary Williams",
    phoneNumber: "+2348098765432",
    dateTime: DateTime.now(),
    referenceNumber: "REF5678",
  ),
  Vehicle(
    plateNumber: "GHI789JK",
    name: "Mike Brown",
    model: "Ford Mustang",
    type: "Sports Car",
    color: "Yellow",
    champion: "Samantha Johnson",
    location: "New York, USA",
    analyst: "Peter Lee",
    phoneNumber: "+1-123-456-7890",
    dateTime: DateTime.now(),
    referenceNumber: "REF9012",
  ),
  Vehicle(
    plateNumber: "JKL012MN",
    name: "Emily Smith",
    model: "Chevrolet Camaro",
    type: "Sports Car",
    color: "Black",
    champion: "Jack Johnson",
    location: "Los Angeles, USA",
    analyst: "Sarah Jones",
    phoneNumber: "+1-234-567-8901",
    dateTime: DateTime.now(),
    referenceNumber: "REF3456",
  ),
  Vehicle(
    plateNumber: "MNO345PQ",
    name: "Mark Johnson",
    model: "Nissan Altima",
    type: "Sedan",
    color: "White",
    champion: "Emily Brown",
    location: "Toronto, Canada",
    analyst: "David Lee",
    phoneNumber: "+1-567-890-1234",
    dateTime: DateTime.now(),
    referenceNumber: "REF6789",
  ),
  Vehicle(
    plateNumber: "PQR678ST",
    name: "Samantha Lee",
    model: "Honda Accord",
    type: "Sedan",
    color: "Silver",
    champion: "Mark Smith",
    location: "Sydney, Australia",
    analyst: "Tom Wilson",
    phoneNumber: "+61-123-456-789",
    dateTime: DateTime.now(),
    referenceNumber: "REF2345",
  ),
  Vehicle(
    plateNumber: "STU901VW",
    name: "Tom Brown",
    model: "Toyota Camry",
    type: "Sedan",
    color: "Gray",
    champion: "Sarah Lee",
    location: "London, UK",
    analyst: "Robert Williams",
    phoneNumber: "+44-123-456-7890",
    dateTime: DateTime.now(),
    referenceNumber: "REF5678",
  ),
  Vehicle(
    plateNumber: "VWX234YZ",
    name: "Jack Williams",
    model: "Mercedes-Benz E-Class",
    type: "Luxury Sedan",
    color: "Black",
    champion: "Tom Lee",
    location: "Paris, France",
    analyst: "Sophie Martin",
    phoneNumber: "+33-123-456-789",
    dateTime: DateTime.now(),
    referenceNumber: "REF9012",
  ),
  Vehicle(
    plateNumber: "YZA567BC",
    name: "Sophie Wilson",
    model: "BMW 5 Series",
    type: "Luxury Sedan",
    color: "White",
    champion: "Mike Lee",
    location: "Berlin, Germany",
    analyst: "John Martin",
    phoneNumber: "+49-123-456-789",
    dateTime: DateTime.now(),
    referenceNumber: "REF3456",
  ),
  Vehicle(
    plateNumber: "BCD890EF",
    name: "Robert Johnson",
    model: "Audi A4",
    type: "Luxury Sedan",
    color: "Blue",
    champion: "Sophie Brown",
    location: "Madrid, Spain",
    analyst: "Emily Martin",
    phoneNumber: "+34-123-456-789",
    dateTime: DateTime.now(),
    referenceNumber: "REF6789",
  ),
];

/// Dummy list of checked out vehicles
List<Vehicle> dummyCheckedOutVehicles = [
  Vehicle(
    plateNumber: "ABC123DE",
    name: "John Doe",
    model: "Honda Civic",
    type: "Sedan",
    color: "Red",
    champion: "Jane Smith",
    location: "Lagos, Nigeria",
    analyst: "David Johnson",
    phoneNumber: "+2348012345678",
    dateTime: DateTime.now(),
    referenceNumber: "REF1234",
  ),
  Vehicle(
    plateNumber: "EFG456HI",
    name: "Sarah Williams",
    model: "Toyota Corolla",
    type: "Sedan",
    color: "Blue",
    champion: "Michael Brown",
    location: "Abuja, Nigeria",
    analyst: "Jennifer Lee",
    phoneNumber: "+2348098765432",
    dateTime: DateTime.now(),
    referenceNumber: "REF5678",
  ),
  Vehicle(
    plateNumber: "JKL789MN",
    name: "Oluwaseun Adeyemi",
    model: "Ford Mustang",
    type: "Sports Car",
    color: "Yellow",
    champion: "Adebisi Olumide",
    location: "Ibadan, Nigeria",
    analyst: "Olumide Adewale",
    phoneNumber: "+2348034567890",
    dateTime: DateTime.now(),
    referenceNumber: "REF9012",
  ),
  Vehicle(
    plateNumber: "PQR012ST",
    name: "Fatima Ahmed",
    model: "Nissan Altima",
    type: "Sedan",
    color: "Silver",
    champion: "Mohammed Abubakar",
    location: "Kano, Nigeria",
    analyst: "Grace Johnson",
    phoneNumber: "+2348023456789",
    dateTime: DateTime.now(),
    referenceNumber: "REF3456",
  ),
  Vehicle(
    plateNumber: "UVW345XY",
    name: "Adewale Ogunyemi",
    model: "Mercedes-Benz C-Class",
    type: "Sedan",
    color: "Black",
    champion: "Olumide Ojo",
    location: "Abeokuta, Nigeria",
    analyst: "Tolu Adebayo",
    phoneNumber: "+2348056789012",
    dateTime: DateTime.now(),
    referenceNumber: "REF7890",
  ),
  Vehicle(
    plateNumber: "ZAB678CD",
    name: "Chinonso Eze",
    model: "BMW X5",
    type: "SUV",
    color: "White",
    champion: "Obinna Nwosu",
    location: "Enugu, Nigeria",
    analyst: "Nneka Uche",
    phoneNumber: "+2348076543210",
    dateTime: DateTime.now(),
    referenceNumber: "REF2345",
  ),
  Vehicle(
    plateNumber: "EFG901HI",
    name: "Aisha Ali",
    model: "Toyota RAV4",
    type: "SUV",
    color: "Red",
    champion: "Yusuf Ibrahim",
    location: "Abuja, Nigeria",
    analyst: "Nkechi Obi",
    phoneNumber: "+2348090123456",
    dateTime: DateTime.now(),
    referenceNumber: "REF6789",
  ),
  Vehicle(
    plateNumber: "LND872AQ",
    name: "Oluwatoyin Adeyemi",
    model: "Toyota Camry",
    type: "Sedan",
    color: "Gray",
    champion: "Helen James",
    location: "Ibadan",
    analyst: "Tayo Bakare",
    phoneNumber: "08023456789",
    dateTime: DateTime.now(),
    referenceNumber: "REF-123456789",
  ),
  Vehicle(
    plateNumber: "ABC123FG",
    name: "Femi Williams",
    model: "Mercedes Benz",
    type: "Coupe",
    color: "Black",
    champion: "David Johnson",
    location: "Lagos",
    analyst: "Bukky Adeniyi",
    phoneNumber: "08012345678",
    dateTime: DateTime.now(),
    referenceNumber: "REF-234567890",
  ),
  Vehicle(
    plateNumber: "KJA443GF",
    name: "Ifeanyi Nwankwo",
    model: "Honda Accord",
    type: "Sedan",
    color: "White",
    champion: "Amina Mohammed",
    location: "Abuja",
    analyst: "Emeka Eze",
    phoneNumber: "09012345678",
    dateTime: DateTime.now(),
    referenceNumber: "REF-345678901",
  ),
  Vehicle(
    plateNumber: "AAA111AK",
    name: "Chika Okoro",
    model: "Ford Explorer",
    type: "SUV",
    color: "Blue",
    champion: "Tunde Adebayo",
    location: "Port Harcourt",
    analyst: "Bola Adeleke",
    phoneNumber: "08098765432",
    dateTime: DateTime.now(),
    referenceNumber: "REF-456789012",
  ),
  Vehicle(
    plateNumber: "FST907BN",
    name: "Tolu Oladele",
    model: "Nissan Altima",
    type: "Sedan",
    color: "Red",
    champion: "Sarah Smith",
    location: "Kano",
    analyst: "Yinka Balogun",
    phoneNumber: "08011223344",
    dateTime: DateTime.now(),
    referenceNumber: "REF-567890123",
  ),
  Vehicle(
    plateNumber: "KED190EF",
    name: "Chidi Nwankwo",
    model: "Toyota Highlander",
    type: "SUV",
    color: "Silver",
    champion: "Sandra Peters",
    location: "Enugu",
    analyst: "Adeola Akindele",
    phoneNumber: "09023456789",
    dateTime: DateTime.now(),
    referenceNumber: "REF-678901234",
  ),
  Vehicle(
    plateNumber: "LND 550 TG",
    name: "Blessing Ibrahim",
    model: "Jeep Wrangler",
    type: "SUV",
    color: "Green",
    champion: "Chris Johnson",
    location: "Lagos",
    analyst: "Efe Ojo",
    phoneNumber: "08056789012",
    dateTime: DateTime.now(),
    referenceNumber: "REF-789012345",
  ),
];
