import 'package:max_task/models/vehicle.dart';

List<Vehicle> vehicles = [
  Vehicle(
    plateNumber: "ABC123DE",
    name: "John Doe",
    model: "Honda Civic",
    type: "Sedan",
    color: "Red",
    champion: "Jane Smith",
    location: "Lagos, Nigeria",
    analyst: "David Johnson",
    phoneNumber: "+2348012345678",
    dateTime: DateTime.now(),
    referenceNumber: "REF1234",
  ),
  Vehicle(
    plateNumber: "EFG456HI",
    name: "Sarah Williams",
    model: "Toyota Corolla",
    type: "Sedan",
    color: "Blue",
    champion: "Michael Brown",
    location: "Abuja, Nigeria",
    analyst: "Jennifer Lee",
    phoneNumber: "+2348098765432",
    dateTime: DateTime.now(),
    referenceNumber: "REF5678",
  ),
  Vehicle(
    plateNumber: "JKL789MN",
    name: "Oluwaseun Adeyemi",
    model: "Ford Mustang",
    type: "Sports Car",
    color: "Yellow",
    champion: "Adebisi Olumide",
    location: "Ibadan, Nigeria",
    analyst: "Olumide Adewale",
    phoneNumber: "+2348034567890",
    dateTime: DateTime.now(),
    referenceNumber: "REF9012",
  ),
  Vehicle(
    plateNumber: "PQR012ST",
    name: "Fatima Ahmed",
    model: "Nissan Altima",
    type: "Sedan",
    color: "Silver",
    champion: "Mohammed Abubakar",
    location: "Kano, Nigeria",
    analyst: "Grace Johnson",
    phoneNumber: "+2348023456789",
    dateTime: DateTime.now(),
    referenceNumber: "REF3456",
  ),
  Vehicle(
    plateNumber: "UVW345XY",
    name: "Adewale Ogunyemi",
    model: "Mercedes-Benz C-Class",
    type: "Sedan",
    color: "Black",
    champion: "Olumide Ojo",
    location: "Abeokuta, Nigeria",
    analyst: "Tolu Adebayo",
    phoneNumber: "+2348056789012",
    dateTime: DateTime.now(),
    referenceNumber: "REF7890",
  ),
  Vehicle(
    plateNumber: "ZAB678CD",
    name: "Chinonso Eze",
    model: "BMW X5",
    type: "SUV",
    color: "White",
    champion: "Obinna Nwosu",
    location: "Enugu, Nigeria",
    analyst: "Nneka Uche",
    phoneNumber: "+2348076543210",
    dateTime: DateTime.now(),
    referenceNumber: "REF2345",
  ),
  Vehicle(
    plateNumber: "EFG901HI",
    name: "Aisha Ali",
    model: "Toyota RAV4",
    type: "SUV",
    color: "Red",
    champion: "Yusuf Ibrahim",
    location: "Abuja, Nigeria",
    analyst: "Nkechi Obi",
    phoneNumber: "+2348090123456",
    dateTime: DateTime.now(),
    referenceNumber: "REF6789",
  ),
];
